USE [master]
GO

/****** Object:  Database [NexosData]    Script Date: 11/01/2021 6:51:49 p. m. ******/
CREATE DATABASE [NexosData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NexosData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NexosData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NexosData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NexosData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NexosData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NexosData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NexosData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NexosData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NexosData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NexosData] SET ARITHABORT OFF 
GO

ALTER DATABASE [NexosData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NexosData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NexosData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NexosData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NexosData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NexosData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NexosData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NexosData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NexosData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NexosData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NexosData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NexosData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NexosData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NexosData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NexosData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NexosData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NexosData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NexosData] SET RECOVERY FULL 
GO

ALTER DATABASE [NexosData] SET  MULTI_USER 
GO

ALTER DATABASE [NexosData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NexosData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NexosData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NexosData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NexosData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NexosData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NexosData] SET  READ_WRITE 
GO


